# Generated by Django 3.2.23 on 2023-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_profiles_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../pp5-wt/default-profile-pic', upload_to='images/pp5-wt/'),
        ),
    ]
