# Generated by Django 3.2.23 on 2023-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default-profile-pic', upload_to='images/pp5-wt/'),
        ),
    ]
